---
title: "5792 Final exam Andrei Matveev R code"
output: html_notebook
---

```{r Problem 1}
#1a
N=10^8
t = runif(1,0,3)
s = t+runif(1,0,3)

Zt = rnorm(N, 0, sqrt(t))
Zs = Zt+rnorm(N, 0, sqrt(s-t))
#1a
cat("mean(Zs*Zt) =", mean(Zs*Zt), "; t =",  t)
#1b
cat("mean(Zs*Zt*Zt) = ", mean(Zs*Zt*Zt))
#1c
cat("the mean = ", mean(Zs*Zt^3), "; 3*t^2 = ",  3*t^2)
rm(Zt, Zs)
```

```{r Problem 2}
dt=10^-7
T = runif(1,0,1)
Z=0
I_dZ = 0
I_dt = 0
for (i in (1:(T/dt))) {
  dZ = rnorm(1, 0, sqrt(dt))
  I_dZ = I_dZ + cos(Z) * dZ
  I_dt = I_dt - sin(Z) * dt
  Z = Z + dZ
}
cat("integral dZ = ", I_dZ,"; sin(Z) - 0.5 * I_dt = ", sin(Z) - 0.5 * I_dt)

```

```{r Problem 3}
dt = 10^-5
sd = sqrt(dt) #for comp efficiency
N=1000
a = 1
mb = -0.5 # mb goes for "minus b", not to mess it up later
mc = -1

run_bm = function(a, mb, mc) {
  flag_Ta = FALSE
  flag_Tmb = FALSE
  flag_Tmc = FALSE
  Z=0
  while (TRUE) {
    dZ = rnorm(1, 0, sd = sd)
    Z = Z + dZ
    if (Z > a) {
      flag_Ta = TRUE
      break
    }
    if (Z < mb) {flag_Tmb = TRUE}
    if (Z < mc) {
      flag_Tmc = TRUE
      break
    }
  }
  return(list(flag_Ta, flag_Tmb, flag_Tmc))
}

outcome = array(NA, dim=N)
for (i in (1:N)) {
  f = run_bm(a = a, mb = mb, mc = mc)
  if (f[3] == TRUE) {
    outcome[i] = 1
  } else {
      if (f[2] == TRUE) {
        outcome[i] = 2
      } else {
          if (f[1] == TRUE) {
            outcome[i] = 3
          } else {outcome[i] = 4} # not possible if work correctly, just a quality check
      }
    }
  cat("\r Brownian motion run #", i, "out of ", N)
}
cat("P(m(T_a) < -b | T_a < T_-c) ", sum(outcome == 2)/(sum(outcome == 2) + sum(outcome == 3)))
hist(outcome)

```

```{r Problem 4_a hard way}
T = 1 # time of interest
m1 = 2 # mu1 for state 1
m2 = 3 # mu2 for state 2
l1 = 10 # lambda1 for state 1
l2 = 30 # lambda2 for state 2

run_the_chain = function(T=1) {
  t = 0 # current time
  t_state_1 = 0 # total time in state 1
  t_state_2 = 0 # total time in state 2
  state = 1 # starting state
  N = 0     # the total number of customers that have entered the store
  
  while (t < T) {
    flag = 0 # flag to track a customer who entered after time T
    if (state == 1) {
      t_arr = rexp(1,l1) # time when the next costemer appears
      t_next_state = rexp(1,m1) # time when we go to the next state
    } else {
      t_arr = rexp(1,l2)
      t_next_state = rexp(1,m2)
    }
    
    if (t_arr < t_next_state) {
      t = t + t_arr
      if (state == 1) {
        t_state_1 = t_state_1 + t_arr
      } else {
        t_state_2 = t_state_2 + t_arr
      }      
      N = N + 1
      flag = 1
    } else {
      t = t + t_next_state
      if (state == 1) {
        t_state_1 = t_state_1 + t_next_state
      } else {
        t_state_2 = t_state_2 + t_next_state
      }   
      if (state == 1) {state = 2} else {state = 1} # switch state
      flag = 0
    }
  }
  if (flag ==1) {
    N = N - 1 # deduction because arrival is after time T AND state was not changed
    if (state == 1) {t_state_1 = t_state_1 - (t - 1)} else {t_state_2 = t_state_2 - (t - 1)}
  } else {
    if (state == 1) {t_state_2 = t_state_2 - (t - 1)} else {t_state_1 = t_state_1 - (t - 1)}
  }
return(array(c(N, t_state_1, t_state_2)))
}

EN = 0
Iter = 10^5
for (i in (1:Iter)) {
  bm = run_the_chain(T=T)
  EN = EN + bm[1]
}
(EN = EN/Iter)
```

```{r Problem 4_a simple way}
T = 1 # time of interest
l1 = 10 # lambda1 for state 1
l2 = 30 # lambda2 for state 2
m1 = 2 # mu1 for state 1
m2 = 3 # mu2 for state 2

EN = 0
Iter = 10^6
for (i in (1:Iter)) {
  t = 0         # current time
  t_state_1 = 0 # total time in state 1
  t_state_2 = 0 # total time in state 2
  state = 1     # starting state

  while (t < T) {
    if (state == 1) {
      t_next_state = rexp(1, m1) # time when we go to the next state
      t_state_1 = t_state_1 + t_next_state
      state = 2
    } else {
      t_next_state = rexp(1, m2)
      t_state_2 = t_state_2 + t_next_state
      state = 1
    }
    t = t + t_next_state
  
  }
  if (state == 2) {t_state_1 = t_state_1 - (t - 1)} else {t_state_2 = t_state_2 - (t - 1)}
  # deduction because arrival is after time T

  EN = EN + l1 * t_state_1 + l2 * t_state_2 # means of arrivals for Poisson lambda over time t 
}
(EN = EN/Iter)

```

```{r Problem 4_b analytical}
library(expm)
T=0.12345
Q_hat = matrix(data = c(-l1-m1, m1, m2,-l2-m2),
           nrow=2, ncol=2, 
           byrow = TRUE)
(expm(Q_hat * T)%*%c(1,1))[1]
                    
```

```{r Problem 4_b based on the hard way}

T = 0.12345 # time of interest
m1 = 2 # mu1 for state 1
m2 = 3 # mu2 for state 2
l1 = 10 # lambda1 for state 1
l2 = 30 # lambda2 for state 2
no_arr = 0
Iter = 10^7
for (i in (1:Iter)) {
  bm = run_the_chain(T=T)
  if (bm[1] == 0) {no_arr = no_arr + 1}
}
cat("frequency of no arrival", no_arr/Iter)

```

```{r Problem 5}
dt = 10^-5
T = 2
sd = sqrt(dt) #for comp efficiency
N=100000 # number of Brownian motion chains
resolution = 0.1 # resolution of the VAR path
Z=0
int_dZ = 0
int_dt = 0
t = 0
ind = 0
var_df = as.data.frame(array(NA, dim = c(T/resolution,3), 
                             dimnames = list(c(), c("Time","Var_int_ZdZ", "Var_Ito's"))))
for (i in (1:(T/dt))) {
  dZ = rnorm(N, 0, sd = sd)
  int_dZ = int_dZ + (Z^2) * dZ
  int_dt = int_dt + Z * dt
  if (t > resolution) {
    ind = ind + 1
    var_df$Time[ind] = i*dt
    var_df$Var_int_ZdZ[ind] = var(int_dZ)
    var_df$`Var_Ito's`[ind] = var((Z^3)/3 - int_dt)
    t = 0
    cat("\r Brownian motion time #", i*dt, "out of ", T)
  }
  t=t+dt
  Z = Z + dZ
}

cat("var(int_dZ) = ", var(int_dZ), "var(ito's) = ", var((Z^3)/3 - int_dt) )
plot(var_df$Time, var_df$Var_int_ZdZ)
```

```{r Problem 5 not efficient}
dt = 10^-5
T = runif(1,0,3)
sd = sqrt(dt) #for comp efficiency
N=100

run_bm = function(T, dt) {
  Z=0
  int_dZ = 0
  int_dt = 0
  for (i in (1:(T/dt))) {
    dZ = rnorm(1, 0, sd = sd)
    int_dZ = int_dZ + (Z^2) * dZ
    int_dt = int_dt + Z * dt
    Z = Z + dZ
  
  }
  return(list(int_dZ, int_dt, Z))
}
f = run_bm(T, dt)
cat("int_dZ = ", f[[1]], "ito's = ", (f[[3]]^3)/3 - f[[2]] )

E_dZ = 0
V_dZ = 0
E_ito = 0
V_ito = 0
for (i in (1:N)) {
  f = run_bm(T, dt)
  ito = (f[[3]]^3)/3 - f[[2]]
  int_dZ = f[[1]]
  E_dZ = E_dZ + int_dZ
  V_dZ = V_dZ + int_dZ^2
  E_ito = E_ito + ito
  V_ito = V_ito + ito^2
  cat("\r Brownian motion run #", i, "out of ", N)
  }
(var_dZ = V_dZ/N - (E_dZ/N)^2)
(var_ito = V_ito/N - (E_ito/N)^2)
```

